name: Deploy HyperTrack Pro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  audit-dependencies:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            hypertrack-pro-v2/package-lock.json
      - name: Install root
        run: npm ci
      - name: Install frontend
        working-directory: hypertrack-pro-v2
        run: npm ci
      - name: Run audit (info only)
        run: |
          npm audit --audit-level=high || true
          cd hypertrack-pro-v2 && npm audit --audit-level=high || true
  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hypertrack-pro-v2

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: hypertrack-pro-v2/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        CI: true
      run: npm test -- --watch=false --ci --passWithNoTests

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [test-frontend]
    defaults:
      run:
        working-directory: hypertrack-pro-v2

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: hypertrack-pro-v2/package-lock.json

    - name: Install and build
      run: |
        npm ci
        npm run build

    - name: Upload frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: hypertrack-pro-v2/build
        retention-days: 1

  notify:
    name: Notify CI Status
    runs-on: ubuntu-latest
    needs: [build-frontend]
    if: always()

    steps:
    - name: Summarize
      run: |
        echo "Build result: ${{ needs.build-frontend.result }}"